In [24]:
%autosave 0

Autosave disabled


## string
capitalize()	Converts the first character to upper case\
count()	Returns the number of times a specified value occurs in a string\
endswith()	Returns true if the string ends with the specified value\
find()	Searches the string for a specified value and returns the position of where it was found, if not found, returns -1\
format()	Formats specified values in a string\
index()	Searches the string for a specified value and returns the position of where it was found, if not found, raises ValueError\
isalnum()	Returns True if all characters in the string are alphanumeric\
isalpha()	Returns True if all characters in the string are in the alphabet\
isdecimal()	Returns True if all characters in the string are decimals\
isdigit()	Returns True if all characters in the string are digits\
islower()	Returns True if all characters in the string are lower case\
isnumeric()	Returns True if all characters in the string are numeric\
isspace()	Returns True if all characters in the string are whitespaces\
istitle()	Returns True if the string follows the rules of a title\
isupper()	Returns True if all characters in the string are upper case\
join()	Joins the elements of an iterable to the end of the string\
ljust()	Returns a left justified version of the string\
lower()	Converts a string into lower case\
lstrip()	Returns a left trim version of the string\
replace()	Returns a string where a specified value is replaced with a specified value\
rfind()	Searches the string for a specified value and returns the last position of where it was found\
rindex()	Searches the string for a specified value and returns the last position of where it was found\
rjust()	Returns a right justified version of the string\
rsplit()	Splits the string at the specified separator, and returns a list\
rstrip()	Returns a right trim version of the string\
split()	Splits the string at the specified separator, and returns a list\
startswith()	Returns true if the string starts with the specified value\
strip()	Returns a trimmed version of the string\
swapcase()	Swaps cases, lower case becomes upper case and vice versa\
title()	Converts the first character of each word to upper case\
upper()	Converts a string into upper case\
zfill()	Fills the string with a specified number of 0 values at the beginning\

### format

In [25]:
"""First letter: {0}. Last letter: {1}.""".format('A', 'Z')

'First letter: A. Last letter: Z.'

In [26]:
"""First letter: {first}. Last letter: {last}.""".format(last='Z', first='A')

'First letter: A. Last letter: Z.'

In [27]:
pi = 3.14159
"pi = {0:.3f}".format(pi)

'pi = 3.142'

### concatenate strings

In [28]:
str1 = 'hello'
str2 = 'world'
str1+" "+str2

'hello world'

In [29]:
str1 = 'hello'
str2 = 'world'
' '.join([str1,str2]) 

'hello world'

In [30]:
"{} {}".format(str1,str2)

'hello world'

In [31]:
f"{str1} {str2}"

'hello world'

In [32]:
print(str1,str2) # concatenate with a single space, change with sep=

hello world


### regex 
escape . \ + * ? [ ^ ] $ ( ) { } | -

abc…	   Letters\
123…	   Digits\
\d	       Any Digit\
\D	       Any Non-digit character\
.	       Any Character\
\.	       Period\
[abc]	   Only a, b, or c\
[^abc]	   Not a, b, nor c\
[a-z]	   Characters a to z\
[0-9]	   Numbers 0 to 9\
\w	       Any Alphanumeric character\
\W	       Any Non-alphanumeric character\
{m}	       m Repetitions\
{m,n}	   m to n Repetitions\
\*	       Zero or more repetitions\
\+	       One or more repetitions\
?	       Optional character\
\s	       Any Whitespace\
\S	       Any Non-whitespace character\
^…$	       Starts and ends\
(…)	       Capture Group\
(a(bc))	   Capture Sub-group\
(.*)	   Capture all\
(abc|def)  Matches abc or def\

pattern_matcher = re.compile(pattern)\
match = pattern_matcher.search(string)\
match.group()\
match.start()\
match.end()\
match.span()\

re.match() - Determine if the regular expression (RE) matches at the beginning of the string.\
re.search() - Scan through a string, looking for any location where this RE matches.\
re.findall() - Find all substrings where the RE matches, and returns them as a list.\
re.finditer() - Find all substrings where the RE matches, and returns them as an iterator.

In [33]:
import re
print(re.search('(ab)c','abcabcabd')) # a match object, only finds the first
print(re.search('(ab)c','abcabcabd').group()) # returns the first match, doesn't extract the pattern group
print(re.search('(a|b)c','accabcabd').groups()) # finds the first match and extracts the pattern group in a tuple
print(re.findall('(a|b)c','accabcabd')) # returns the list and extracts the pattern groups

<re.Match object; span=(0, 3), match='abc'>
abc
('a',)
['a', 'b']


In [34]:
# find words in a sentence. a word can include one apostrophe if it is followed by any character
pattern = r"[a-z]+(?:'[a-z]+)?"  # ?: allows to quantify the stuff inbetween() without capturing it
re.findall(pattern,"I'm sorry, sir, but this is a 'gluten-free' restaurant. We don't serve bread.".lower())

["i'm",
 'sorry',
 'sir',
 'but',
 'this',
 'is',
 'a',
 'gluten',
 'free',
 'restaurant',
 'we',
 "don't",
 'serve',
 'bread']

In [35]:
pattern1 = r'A.*Z' # * is greedy, matches as long as possible
pattern2 = r'A.*?Z' # ? turns off greedy match
print(re.findall(pattern1,'eeeAiiZuuuuAoooZeeee'))
print(re.findall(pattern2,'eeeAiiZuuuuAoooZeeee'))

['AiiZuuuuAoooZ']
['AiiZ', 'AoooZ']


In [36]:
# backslash plague
input_with_slash_section = "This string contains `\section`, which we would like to match."

print(re.search("\section", input_with_slash_section))
print(re.search("\\section", input_with_slash_section))
print(re.search("\\\\section", input_with_slash_section))

# with raw string, although the interpreter won't process the backslash, the regular expression processor will do so
print(re.search(r"\section", input_with_slash_section))
print(re.search(r"\\section", input_with_slash_section))
print(re.search(r"\\\\section", input_with_slash_section))

None
None
<re.Match object; span=(22, 30), match='\\section'>
None
<re.Match object; span=(22, 30), match='\\section'>
None


## list
sort(): Sorts the list in ascending order.

append(): Adds one element to a list.

extend(): Adds multiple elements to a list.

index(): Returns the first appearance of a particular value.

type(list): It returns the class type of an object.

max(list): It returns an item from the list with a max value.

min(list): It returns an item from the list with a min value.

len(list): It gives the overall length of the list.

sum(list): Calculates sum of all the elements of the list.

clear(): Removes all the elements from the list.

insert(): Adds a component at the required position.

count(): Returns the number of elements with the required value.

pop(): Removes the element at the required position.

remove(): Removes the primary item with the desired value.

reverse(): Reverses the order of the list.

copy(): Returns a duplicate of the list.

### list.sort() vs sorted()

In [37]:
lst1 = [1,2,6,5]
lst2 = lst1.sort() # modify lst1 in place, lst2 will be None
print(lst1,lst2)

lst1 = [1,2,6,5]
lst2 = sorted(lst1) # lst1 doesn't change
print(lst1, lst2)

[1, 2, 5, 6] None
[1, 2, 6, 5] [1, 2, 5, 6]


- 下面是自定义排序\
a = ['x', 'z', 'y']\
dic = {'x': 0, 'y': 1, 'z': 2}


- 我想让a中的元素按照他们在dic中对应的value排序\
a.sort(key = lambda x: dic[x])\
b = sorted(a, key = lambda x: dic[x])


- Python排序默认从小到大，如果想从大到小，可以加负号，比如\
a.sort(key = lambda x: -dic[x])\
- 或者\
a.sort(key = lambda x: dic[x], reverse = True)

### concatenate lists

In [38]:
mylist1 = [11, 13, 15, 17, 19]
mylist2 = [23, 25, 27, 29, 31]
mylist3 = mylist1+mylist2
mylist3

[11, 13, 15, 17, 19, 23, 25, 27, 29, 31]

In [39]:
mylist1 = [11, 13, 15, 17, 19]
mylist2 = [23, 25, 27, 29, 31]
mylist3 = mylist1.extend(mylist2) # directly modify mylist1, mylist3 will be None
print(mylist1)
print(mylist3)

[11, 13, 15, 17, 19, 23, 25, 27, 29, 31]
None


In [40]:
mylist1 = [11, 13, 15, 17, 19]
mylist2 = [23, 25, 27, 29, 31]
# using * operator to concatenate lists
mylist3 = [*mylist1, *mylist2]
mylist3

[11, 13, 15, 17, 19, 23, 25, 27, 29, 31]

In [41]:
mylist1 = [11, 13, 15, 17, 19]
mylist2 = [23, 25, 27, 29, 31]
# using list comprehension to concatenate lists
mylist3 = [b for a in [mylist1, mylist2] for b in a]
mylist3

[11, 13, 15, 17, 19, 23, 25, 27, 29, 31]

### list() vs []
list() is a function that will iterate the values of s1&s2 and return a list with those values. [] is a list literal and does not parse the iterable set passed to it.

In [42]:
set1 = {'a','b'}
set2 = {'b','c'}

lst1 = list(set1&set2)
lst2 = [set1&set2]

print(lst1)
print(lst2)

['b']
[{'b'}]


### make an empty list of size n

In [43]:
lst = [None]*8
lst

[None, None, None, None, None, None, None, None]

### list comprehension

In [44]:
[val if val % 2 else -val
 for val in range(20) if val % 3]

[1, -2, -4, 5, 7, -8, -10, 11, 13, -14, -16, 17, 19]

## Set
add()	                        Adds an element to the set

clear()	                        Removes all the elements from the set

copy()	                        Returns a copy of the set

difference()	                Returns a set containing the difference between two or more sets

difference_update()	            Removes the items in this set that are also included in another, specified set

discard()	                    Remove the specified item

intersection()	                Returns a set, that is the intersection of two or more sets
 
intersection_update()	        Removes the items in this set that are not present in other, specified set(s)

isdisjoint()	                Returns whether two sets have a intersection or not

issubset()	                    Returns whether another set contains this set or not

issuperset()	                Returns whether this set contains another set or not

pop()	                        Removes an element from the set

remove()	                    Removes the specified element

symmetric_difference()	        Returns a set with the symmetric differences of two sets

symmetric_difference_update()	Inserts the symmetric differences from this set and another

union()	                        Return a set containing the union of sets

update()	                    Update the set with another set, or any other iterable

Values are not limited to integers and, like lists, elements may mix types. However, the elements must be immutable. Recall that the primitive built-in types (e.g., int, float, str, bool) are immutable, as is tuple. However, a list is mutable, and therefore cannot be a set element.
> There is a subtlety -- although tuple is immutable, you can construct a tuple that contains mutable values, e.g., the triple (1, 2, [3, 4, 5]) where the third element is a list, which is mutable. This tuple would, therefore, be an invalid set element.

In [45]:
E = {'cat', 1.61803398875, ('a', 'b', 'c')}
# E.add([1, 2, 3]) # Error!
print(E)

T1 = (1,2,[3,4,5])
# set(T1) # Error!
T2 = (1,2,3,4,5)
set(T2)

{'cat', 1.61803398875, ('a', 'b', 'c')}


{1, 2, 3, 4, 5}

set初始化\
a = set() # 空的set\
a = set([1, 2, 2, 3]) # 用一个list初始化这个set，里面重复的元素会被干掉\
a = {1, 2, 3} # 用一个常量set初始化这个set

a.add(4) # 向set里面添加值\
a.update({-1, -2, -3}) # 添加多个值

set基本操作\
a = set()\
b = set()\
c = a | b # 并集 # union\
c = a & b # 交集 # intersection\
c = a - b # 差集 # difference\
c = a ^ b # (a | b) - (a & b)\
c = a < b # proper subset (use `<=` for subset, `>` or `>=` for superset, or '==' for equality)

## dictionary
clear()	        Removes all the elements from the dictionary

copy()      	Returns a copy of the dictionary

fromkeys()  	Returns a dictionary with the specified keys and value

get()	        Returns the value of the specified key

items()	        Returns a list containing a tuple for each key value pair

keys()	        Returns a list containing the dictionary's keys

pop()	        Removes the element with the specified key

popitem()	    Removes the last inserted key-value pair

setdefault()	Returns the value of the specified key. If the key does not exist: insert the key, with the specified value

update()	    Updates the dictionary with the specified key-value pairs

values()	    Returns a list of all the values in the dictionary

In [46]:
a = {'p': 'as', 'o': 1, 'j': 4}

# 遍历key
for i in a: # or a.keys()
  print(i, a[i])

# 遍历value
for i in a.values():
  print(i)

# 同时遍历key和value：
for k, v in a.items():
  print(k, v)

p as
o 1
j 4
as
1
4
p as
o 1
j 4


### default dictionary

In [47]:
a = {}
a['key']='value'

In [48]:
from collections import defaultdict
a = defaultdict(int)
print(a['key']) # 这里会输出0

a = defaultdict(list)
print(a['key']) # 这里会输出[]（一个空的list）

0
[]


### dictionary comprehension

In [49]:
english = "one two three four five six seven eight nine ten".split()
print(english)

french = "un deux trois quatre cinq six sept huit neuf dix".split()
print(french)

e2f = {k: v for k, v in zip(english, french)} # Dictionary comprehension
print(e2f['three'])

['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']
['un', 'deux', 'trois', 'quatre', 'cinq', 'six', 'sept', 'huit', 'neuf', 'dix']
trois


## Tuples

A tuple is a read-only ("immutable") fixed-length sequence of values.


In [50]:
# 可以直接从list来初始化tuple
a = tuple([1, 2]) # a = (1, 2)

# tuple和list相比，最大的特点就是，一旦定义，不可改变长度以及内容，就像一个常数一样使用

# tuple的这个特性可以让我们用来同时比较多个数是否都相等
a = (1, 2)
b = (1, 2)
a == b # True

a = (1, 3)
a == b # False

False

## iterator and generator

In [51]:
L = [n ** 2 for n in range(12)] # list
for val in L:
    print(val, end=' ')

0 1 4 9 16 25 36 49 64 81 100 121 

In [52]:
G = (n ** 2 for n in range(12)) # generator expression. does not actually compute the values until they are needed
for val in G:
    print(val, end=' ')

0 1 4 9 16 25 36 49 64 81 100 121 

In [53]:
I = iter([n ** 2 for n in range(12)]) # iterator
for val in I:
    print(val, end=' ')

0 1 4 9 16 25 36 49 64 81 100 121 

In [54]:
S = {n ** 2 for n in range(12)} # set iterator
for val in S:
    print(val, end=' ')

0 1 64 121 4 36 100 9 16 49 81 25 

### itertools

In [55]:
zoo = {'cat', 'dog', 'emu', 'zebra'}  # a set of animals

from itertools import combinations    # Try also: `permutations`
for x in combinations(zoo, 3):      
    print(x)

('zebra', 'cat', 'emu')
('zebra', 'cat', 'dog')
('zebra', 'emu', 'dog')
('cat', 'emu', 'dog')


### filter
filter: an iterator that only yields values for which a given predicate function evalutes to True.

In [56]:
# find values up to 10 for which x % 2 is zero
is_even = lambda x: x % 2 == 0
print(is_even(4), is_even(7), "\n")

for val in filter(is_even, range(10)):
    print(val, end=' ')

True False 

0 2 4 6 8 

### map
map: an iterator that first applies a given function to each value.

In [57]:
# find the first 10 square numbers
square = lambda x: x ** 2
for val in map(square, range(10)):
    print(val, end=' ')

0 1 4 9 16 25 36 49 64 81 

### enumarate
enumerate(x): an iterator that produces the elements of x along with a "running count" that starts at 0.

In [58]:
a = enumerate('alsdfkj')
print(a)
print(*enumerate('alsdfkj')) # An iterator can be converted into an argument tuple using the *i syntax 

(0, 'a') (1, 'l') (2, 's') (3, 'd') (4, 'f') (5, 'k') (6, 'j')


In [59]:
for i, s in enumerate('alsdfkj'):
    print(f'{i}: {s}')

0: a
1: l
2: s
3: d
4: f
5: k
6: j


### zip
Use zip(a, b, ...) to "merge" two or more collections. Conceptually, zip() produces tuples of corresponding elements from each input collection.

In [60]:
c = [2, 4, 6, 8, 'xoxo', 13.4, 2]
b = zip(c,c[::-1])
print(b)
print(*zip(c,c[::-1])) # An iterator can be converted into an argument tuple using the *i syntax 

[(f, b) for f, b in zip(c, c[::-1])]

(2, 2) (4, 13.4) (6, 'xoxo') (8, 8) ('xoxo', 6) (13.4, 4) (2, 2)


[(2, 2), (4, 13.4), (6, 'xoxo'), (8, 8), ('xoxo', 6), (13.4, 4), (2, 2)]

In [61]:
list(zip(c, c[::-1])) # to view the zip object

[(2, 2), (4, 13.4), (6, 'xoxo'), (8, 8), ('xoxo', 6), (13.4, 4), (2, 2)]

In [62]:
dict(zip(c, c[::-1])) # construct a dictionary directly from zip rather than dictionary comprehension

{2: 2, 4: 13.4, 6: 'xoxo', 8: 8, 'xoxo': 6, 13.4: 4}

In [63]:
a = [1,2,3,4]
b = ('a b c d').split()
c = zip(a,b)
# print(*c)  # if print, c would be unpacked and can't continue the next line
d,e = zip(*c) # 'unzip'
print(d,e)

(1, 2, 3, 4) ('a', 'b', 'c', 'd')


### while, break, continue

In [64]:
i = 0
while i < 10:
    print(i, end=' ')
    i += 1

0 1 2 3 4 5 6 7 8 9 

In [65]:
# Print odd integers in [0, 20)
for n in range(20):
    if n % 2 == 0:
        continue
    print(n, end=' ')

1 3 5 7 9 11 13 15 17 19 

In [66]:
# Print Fibonacci sequence for values <= 100
a, b = 0, 1
amax = 100
L = []

while True:
    (a, b) = (b, a + b)
    if a > amax:
        break
    L.append(a)

print(L)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


## pandas
describe()\
info()\
apply(func,axis=0/1) works on a row / column basis of a DataFrame\
applymap() works element-wise on a DataFrame\
map() works element-wise on a Series\
concat([df1,df2],ignore_index=True)\
merge(df1,df2,on='',how='left/right/inner/outer')\
drop(['col1','col2'],axis=1,inplace=True)\
unique() show unique values\
nunique() count how many unique values\
groupby(['col1'],as_index=False)\
count() does not include NaN values\
size() includes NaN values\
value_counts(normalize=True)\
sort_values(by=['col1'],ascending=False,inplace=True)\
reset_index(drop=True,inplace=True)\
set_index('col1') promotes a column to be the index\
set_axis(['col1','col2'],axis='columns',inplace=True) rename columns\
rename(columns = {'Column 1': 'Column_1'}, index = {'Row 1': 'Row_1'}, inplace=True)\
to_frame()\
isin()\
astype({"col1":int})\
fillna(0,inplace=True)\
dropna()\
shape()\
melt() wide to long\
xs()\
query('col1=="string1" and col2==val2')\
groupby().filter() groupby then filter, doesn't do any aggregation\
agg({"col1":"count","col2","mean"})

## numpy

In [67]:
import numpy as np
np.arange(1, 9, 2) # start, end (exclusive), step

array([1, 3, 5, 7])

In [68]:
print(np.linspace(0, 1, 6)) # start, end (inclusive), number of items
print(np.linspace(0, 1, 5, endpoint=False))

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


In [69]:
np.ones((3, 3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.diag([1,2,3]) #integer input=>integer output

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [73]:
np.empty((3, 4),dtype=bool)

array([[ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [74]:
print(np.random.rand(4))       # uniform in [0, 1]
print(np.random.randn(4))      # Gaussian

[0.75181902 0.87318659 0.06257803 0.79898857]
[-0.59673006  1.21900346  0.46943429 -3.22761136]


In [75]:
x = np.array([1, 3, 2])
x.min() 
# 1
x.max()
# 3
x.argmin()  # index of minimum
# 0
x.argmax()  # index of maximum
# 1

1

In [76]:
print(np.all([True, True, False]))
print(np.any([True, True, False]))

False
True


In [77]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ravel())
print(a.reshape((2, -1)))    # unspecified (-1) value is inferred

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [78]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

In [79]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [80]:
a = np.arange(4)
a.reshape((2,-1))

array([[0, 1],
       [2, 3]])

In [81]:
a = np.array([1, 2, 3])
a.dtype
# dtype('int64')
a[0] = 1.9     # <-- float is truncated to integer
a

array([1, 2, 3])

In [82]:
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int)  # <-- truncates to integer
b

array([1, 1, 1])

In [83]:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
b                    # still floating-point

array([1., 2., 2., 2., 4., 4.])

## \* unpack

In [84]:
s=[*'abcde']
s

['a', 'b', 'c', 'd', 'e']

In [85]:
*s,='abcde'
s

['a', 'b', 'c', 'd', 'e']

## Saving memory
Running operations can cause new memory to be allocated to host results. For example, if we write Y = X + Y, we dereference the tensor that Y used to point to and instead point Y at the newly allocated memory. We can demonstrate this issue with Python’s id() function, which gives us the exact address of the referenced object in memory. Note that after we run Y = Y + X, id(Y) points to a different location. That’s because Python first evaluates Y + X, allocating new memory for the result and then points Y to this new location in memory.

In [17]:
Y, X = [1,3], [2,4]
before = id(Y)
Y = Y + X
id(Y) == before

False

This might be undesirable for two reasons. First, we do not want to run around allocating memory unnecessarily all the time. In machine learning, we often have hundreds of megabytes of parameters and update all of them multiple times per second. Whenever possible, we want to perform these updates in place. Second, we might point at the same parameters from multiple variables. If we do not update in place, we must be careful to update all of these references, lest we spring a memory leak or inadvertently refer to stale parameters.

In [19]:
Y, X = [1,3], [2,4]
before = id(Y)
Y+=X
id(Y) == before

True

In [20]:
Y, X = [1,3], [2,4]
before = id(Y)
Y[:]=Y+X
id(Y) == before

True

## shallow vs deep copy
A shallow copy creates a new object which stores the reference of the original elements.<br>
So, a shallow copy doesn't create a copy of nested objects, instead it just copies the reference of nested objects. This means, a copy process does not recurse or create copies of nested objects itself.<br>
A deep copy creates a new object and recursively adds the copies of nested objects present in the original elements.

In [13]:
import copy

old_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
# shallow copy
new_list = copy.copy(old_list)
old_list.append([4, 4, 4])

print("Old list:", old_list)
print('ID of Old List:', id(old_list))

print('New List:', new_list)
print('ID of New List:', id(new_list))

Old list: [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]
ID of Old List: 2031854802752
New List: [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
ID of New List: 2031854802240


In [14]:
old_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
# shallow copy
new_list = copy.copy(old_list)
old_list[1][1] = 'AA'

print("Old list:", old_list)
print('ID of Old List:', id(old_list))

print('New List:', new_list)
print('ID of New List:', id(new_list))

Old list: [[1, 1, 1], [2, 'AA', 2], [3, 3, 3]]
ID of Old List: 2031854802624
New List: [[1, 1, 1], [2, 'AA', 2], [3, 3, 3]]
ID of New List: 2031854775488


In [15]:
old_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
# deep copy
new_list = copy.deepcopy(old_list)
old_list.append([4, 4, 4])

print("Old list:", old_list)
print('ID of Old List:', id(old_list))

print('New List:', new_list)
print('ID of New List:', id(new_list))

Old list: [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]
ID of Old List: 2031854822784
New List: [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
ID of New List: 2031854775360


In [16]:
old_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
# deep copy
new_list = copy.deepcopy(old_list)
old_list[1][1] = 'AA'

print("Old list:", old_list)
print('ID of Old List:', id(old_list))

print('New List:', new_list)
print('ID of New List:', id(new_list))

Old list: [[1, 1, 1], [2, 'AA', 2], [3, 3, 3]]
ID of Old List: 2031854759808
New List: [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
ID of New List: 2031854802624
